package currency

const (
	NotApplicable string = "N.A."

	AED alphabeticCode = "AED" // UAE Dirham
	AFN alphabeticCode = "AFN" // Afghani
	ALL alphabeticCode = "ALL" // Lek
	AMD alphabeticCode = "AMD" // Armenian Dram
	ANG alphabeticCode = "ANG" // Netherlands Antillean Guilder
	AOA alphabeticCode = "AOA" // Kwanza
	ARS alphabeticCode = "ARS" // Argentine Peso
	AUD alphabeticCode = "AUD" // Australian Dollar
	AWG alphabeticCode = "AWG" // Aruban Florin
	AZN alphabeticCode = "AZN" // Azerbaijan Manat
	BAM alphabeticCode = "BAM" // Convertible Mark
	BBD alphabeticCode = "BBD" // Barbados Dollar
	BDT alphabeticCode = "BDT" // Taka
	BGN alphabeticCode = "BGN" // Bulgarian Lev
	BHD alphabeticCode = "BHD" // Bahraini Dinar
	BIF alphabeticCode = "BIF" // Burundi Franc
	BMD alphabeticCode = "BMD" // Bermudian Dollar
	BND alphabeticCode = "BND" // Brunei Dollar
	BOB alphabeticCode = "BOB" // Boliviano
	BOV alphabeticCode = "BOV" // Mvdol
	BRL alphabeticCode = "BRL" // Brazilian Real
	BSD alphabeticCode = "BSD" // Bahamian Dollar
	BTN alphabeticCode = "BTN" // Ngultrum
	BWP alphabeticCode = "BWP" // Pula
	BYN alphabeticCode = "BYN" // Belarusian Ruble
	BZD alphabeticCode = "BZD" // Belize Dollar
	CAD alphabeticCode = "CAD" // Canadian Dollar
	CDF alphabeticCode = "CDF" // Congolese Franc
	CHE alphabeticCode = "CHE" // WIR Euro
	CHF alphabeticCode = "CHF" // Swiss Franc
	CHW alphabeticCode = "CHW" // WIR Franc
	CLF alphabeticCode = "CLF" // Unidad de Fomento
	CLP alphabeticCode = "CLP" // Chilean Peso
	CNY alphabeticCode = "CNY" // Yuan Renminbi
	COP alphabeticCode = "COP" // Colombian Peso
	COU alphabeticCode = "COU" // Unidad de Valor Real
	CRC alphabeticCode = "CRC" // Costa Rican Colon
	CUC alphabeticCode = "CUC" // Peso Convertible
	CUP alphabeticCode = "CUP" // Cuban Peso
	CVE alphabeticCode = "CVE" // Cabo Verde Escudo
	CZK alphabeticCode = "CZK" // Czech Koruna
	DJF alphabeticCode = "DJF" // Djibouti Franc
	DKK alphabeticCode = "DKK" // Danish Krone
	DOP alphabeticCode = "DOP" // Dominican Peso
	DZD alphabeticCode = "DZD" // Algerian Dinar
	EGP alphabeticCode = "EGP" // Egyptian Pound
	ERN alphabeticCode = "ERN" // Nakfa
	ETB alphabeticCode = "ETB" // Ethiopian Birr
	EUR alphabeticCode = "EUR" // Euro
	FJD alphabeticCode = "FJD" // Fiji Dollar
	FKP alphabeticCode = "FKP" // Falkland Islands Pound
	GBP alphabeticCode = "GBP" // Pound Sterling
	GEL alphabeticCode = "GEL" // Lari
	GHS alphabeticCode = "GHS" // Ghana Cedi
	GIP alphabeticCode = "GIP" // Gibraltar Pound
	GMD alphabeticCode = "GMD" // Dalasi
	GNF alphabeticCode = "GNF" // Guinean Franc
	GTQ alphabeticCode = "GTQ" // Quetzal
	GYD alphabeticCode = "GYD" // Guyana Dollar
	HKD alphabeticCode = "HKD" // Hong Kong Dollar
	HNL alphabeticCode = "HNL" // Lempira
	HRK alphabeticCode = "HRK" // Kuna
	HTG alphabeticCode = "HTG" // Gourde
	HUF alphabeticCode = "HUF" // Forint
	IDR alphabeticCode = "IDR" // Rupiah
	ILS alphabeticCode = "ILS" // New Israeli Sheqel
	INR alphabeticCode = "INR" // Indian Rupee
	IQD alphabeticCode = "IQD" // Iraqi Dinar
	IRR alphabeticCode = "IRR" // Iranian Rial
	ISK alphabeticCode = "ISK" // Iceland Krona
	JMD alphabeticCode = "JMD" // Jamaican Dollar
	JOD alphabeticCode = "JOD" // Jordanian Dinar
	JPY alphabeticCode = "JPY" // Yen
	KES alphabeticCode = "KES" // Kenyan Shilling
	KGS alphabeticCode = "KGS" // Som
	KHR alphabeticCode = "KHR" // Riel
	KMF alphabeticCode = "KMF" // Comorian Franc
	KPW alphabeticCode = "KPW" // North Korean Won
	KRW alphabeticCode = "KRW" // Won
	KWD alphabeticCode = "KWD" // Kuwaiti Dinar
	KYD alphabeticCode = "KYD" // Cayman Islands Dollar
	KZT alphabeticCode = "KZT" // Tenge
	LAK alphabeticCode = "LAK" // Lao Kip
	LBP alphabeticCode = "LBP" // Lebanese Pound
	LKR alphabeticCode = "LKR" // Sri Lanka Rupee
	LRD alphabeticCode = "LRD" // Liberian Dollar
	LSL alphabeticCode = "LSL" // Loti
	LYD alphabeticCode = "LYD" // Libyan Dinar
	MAD alphabeticCode = "MAD" // Moroccan Dirham
	MDL alphabeticCode = "MDL" // Moldovan Leu
	MGA alphabeticCode = "MGA" // Malagasy Ariary
	MKD alphabeticCode = "MKD" // Denar
	MMK alphabeticCode = "MMK" // Kyat
	MNT alphabeticCode = "MNT" // Tugrik
	MOP alphabeticCode = "MOP" // Pataca
	MRU alphabeticCode = "MRU" // Ouguiya
	MUR alphabeticCode = "MUR" // Mauritius Rupee
	MVR alphabeticCode = "MVR" // Rufiyaa
	MWK alphabeticCode = "MWK" // Malawi Kwacha
	MXN alphabeticCode = "MXN" // Mexican Peso
	MXV alphabeticCode = "MXV" // Mexican Unidad de Inversion (UDI)
	MYR alphabeticCode = "MYR" // Malaysian Ringgit
	MZN alphabeticCode = "MZN" // Mozambique Metical
	NAD alphabeticCode = "NAD" // Namibia Dollar
	NGN alphabeticCode = "NGN" // Naira
	NIO alphabeticCode = "NIO" // Cordoba Oro
	NOK alphabeticCode = "NOK" // Norwegian Krone
	NPR alphabeticCode = "NPR" // Nepalese Rupee
	NZD alphabeticCode = "NZD" // New Zealand Dollar
	OMR alphabeticCode = "OMR" // Rial Omani
	PAB alphabeticCode = "PAB" // Balboa
	PEN alphabeticCode = "PEN" // Sol
	PGK alphabeticCode = "PGK" // Kina
	PHP alphabeticCode = "PHP" // Philippine Peso
	PKR alphabeticCode = "PKR" // Pakistan Rupee
	PLN alphabeticCode = "PLN" // Zloty
	PYG alphabeticCode = "PYG" // Guarani
	QAR alphabeticCode = "QAR" // Qatari Rial
	RON alphabeticCode = "RON" // Romanian Leu
	RSD alphabeticCode = "RSD" // Serbian Dinar
	RUB alphabeticCode = "RUB" // Russian Ruble
	RWF alphabeticCode = "RWF" // Rwanda Franc
	SAR alphabeticCode = "SAR" // Saudi Riyal
	SBD alphabeticCode = "SBD" // Solomon Islands Dollar
	SCR alphabeticCode = "SCR" // Seychelles Rupee
	SDG alphabeticCode = "SDG" // Sudanese Pound
	SEK alphabeticCode = "SEK" // Swedish Krona
	SGD alphabeticCode = "SGD" // Singapore Dollar
	SHP alphabeticCode = "SHP" // Saint Helena Pound
	SLL alphabeticCode = "SLL" // Leone
	SOS alphabeticCode = "SOS" // Somali Shilling
	SRD alphabeticCode = "SRD" // Surinam Dollar
	SSP alphabeticCode = "SSP" // South Sudanese Pound
	STN alphabeticCode = "STN" // Dobra
	SVC alphabeticCode = "SVC" // El Salvador Colon
	SYP alphabeticCode = "SYP" // Syrian Pound
	SZL alphabeticCode = "SZL" // Lilangeni
	THB alphabeticCode = "THB" // Baht
	TJS alphabeticCode = "TJS" // Somoni
	TMT alphabeticCode = "TMT" // Turkmenistan New Manat
	TND alphabeticCode = "TND" // Tunisian Dinar
	TOP alphabeticCode = "TOP" // Pa’anga
	TRY alphabeticCode = "TRY" // Turkish Lira
	TTD alphabeticCode = "TTD" // Trinidad and Tobago Dollar
	TWD alphabeticCode = "TWD" // New Taiwan Dollar
	TZS alphabeticCode = "TZS" // Tanzanian Shilling
	UAH alphabeticCode = "UAH" // Hryvnia
	UGX alphabeticCode = "UGX" // Uganda Shilling
	USD alphabeticCode = "USD" // US Dollar
	USN alphabeticCode = "USN" // US Dollar (Next day)
	UYI alphabeticCode = "UYI" // Uruguay Peso en Unidades Indexadas (UI)
	UYU alphabeticCode = "UYU" // Peso Uruguayo
	UYW alphabeticCode = "UYW" // Unidad Previsional
	UZS alphabeticCode = "UZS" // Uzbekistan Sum
	VED alphabeticCode = "VED" // Bolívar Soberano
	VES alphabeticCode = "VES" // Bolívar Soberano
	VND alphabeticCode = "VND" // Dong
	VUV alphabeticCode = "VUV" // Vatu
	WST alphabeticCode = "WST" // Tala
	XAF alphabeticCode = "XAF" // CFA Franc BEAC
	XAG alphabeticCode = "XAG" // Silver
	XAU alphabeticCode = "XAU" // Gold
	XBA alphabeticCode = "XBA" // Bond Markets Unit European Composite Unit (EURCO)
	XBB alphabeticCode = "XBB" // Bond Markets Unit European Monetary Unit (E.M.U.-6)
	XBC alphabeticCode = "XBC" // Bond Markets Unit European Unit of Account 9 (E.U.A.-9)
	XBD alphabeticCode = "XBD" // Bond Markets Unit European Unit of Account 17 (E.U.A.-17)
	XCD alphabeticCode = "XCD" // East Caribbean Dollar
	XDR alphabeticCode = "XDR" // SDR (Special Drawing Right)
	XOF alphabeticCode = "XOF" // CFA Franc BCEAO
	XPD alphabeticCode = "XPD" // Palladium
	XPF alphabeticCode = "XPF" // CFP Franc
	XPT alphabeticCode = "XPT" // Platinum
	XSU alphabeticCode = "XSU" // Sucre
	XTS alphabeticCode = "XTS" // Codes specifically reserved for testing purposes
	XUA alphabeticCode = "XUA" // ADB Unit of Account
	XXX alphabeticCode = "XXX" // The codes assigned for transactions where no currency is involved
	YER alphabeticCode = "YER" // Yemeni Rial
	ZAR alphabeticCode = "ZAR" // Rand
	ZMW alphabeticCode = "ZMW" // Zambian Kwacha
	ZWL alphabeticCode = "ZWL" // Zimbabwe Dollar
)
